/* midge_main.h */
#ifndef MIDGE_MAIN_H
#define MIDGE_MAIN_H

#include "core/midge_core.h"

const char *code_editor_handle_input_v1_code =
    "printf(\"fehi-0\\n\");\n"
    "\n"
    "if (fedit->data.visual.hidden) {\n"
    "  return;\n"
    "}\n"
    "\n"
    "code_editor_state *state = (code_editor_state *)fedit->extra;\n"
    "\n"
    "event->handled = true;\n"
    "\n"
    "if (event->type == INPUT_EVENT_MOUSE_PRESS) {\n"
    "  if (event->detail.mouse.button == MOUSE_BUTTON_SCROLL_DOWN) {\n"
    "    ++state->line_display_offset;\n"
    "  }\n"
    "  else if (event->detail.mouse.button == MOUSE_BUTTON_SCROLL_UP) {\n"
    "    --state->line_display_offset;\n"
    "  }\n"
    "}\n"
    "else if (event->type == INPUT_EVENT_KEY_PRESS) {\n"
    "  code_editor_handle_keyboard_input(fedit, event);\n"
    "}\n"
    "else {\n"
    "  return;\n"
    "}\n"
    "\n"
    "printf(\"fehi-4\\n\");\n"
    "// Update all modified rendered lines\n"
    "for (int i = 0; i < CODE_EDITOR_RENDERED_CODE_LINES; ++i) {\n"
    "  if (i + state->line_display_offset >= state->text.lines_count) {\n"
    "\n"
    "    printf(\"fehi-5\\n\");\n"
    "    if (!state->render_lines[i].text) {\n"
    "      continue;\n"
    "    }\n"
    "\n"
    "    printf(\"was:'%s' now:NULL\\n\", state->render_lines[i].text);\n"
    "    free(state->render_lines[i].text);\n"
    "    state->render_lines[i].text = NULL;\n"
    "  }\n"
    "  else {\n"
    "    printf(\"fehi-6\\n\");\n"
    "    if (state->render_lines[i].text &&\n"
    "      !strcmp(state->render_lines[i].text, state->text.lines[i + state->line_display_offset])) {\n"
    "      continue;\n"
    "    }\n"
    "\n"
    "    printf(\"fehi-was:'%s' now:'%s'\\n\", state->render_lines[i].text, state->text.lines[i + state->line_display_offset]);\n"
    "    // Update\n"
    "    if (state->render_lines[i].text) {\n"
    "      free(state->render_lines[i].text);\n"
    "    }\n"
    "    allocate_and_copy_cstr(state->render_lines[i].text, state->text.lines[i + state->line_display_offset]);\n"
    "  }\n"
    "\n"
    "  printf(\"fehi-7\\n\");\n"
    "  state->render_lines[i].requires_render_update = true;\n"
    "  fedit->data.visual.requires_render_update = true;\n"
    "}\n";
#endif // MIDGE_CORE_H